server:
  port: 8081

spring:
  datasource:
    url: ""
    driver-class-name: org.postgresql.Driver
    username: nkwenti
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

keycloak:
  realm: ""
  auth-server-url: ""
  client-id: ""
  client-secret: ""
  redirect-uri: ""